#!/usr/bin/env python3

import uvicorn
import asyncio
import time
import codecs
import os
import logging
from base64 import b64decode
from cachetools import TTLCache
from fastapi import FastAPI, Request, Response, Header
from fastapi.exceptions import RequestValidationError
from fastapi.routing import APIRoute
from fastapi.responses import PlainTextResponse
from fastapi.templating import Jinja2Templates
from starlette.exceptions import HTTPException as StarletteHTTPException
from typing import Callable, Annotated
from contextlib import asynccontextmanager
from cryptography.hazmat.primitives.asymmetric.x25519 import X25519PrivateKey
from cryptography.hazmat.primitives import serialization
from jinja2 import Environment, DictLoader


_openapi = FastAPI.openapi


def openapi(self: FastAPI):
    _openapi(self)

    for _, method_item in self.openapi_schema.get("paths").items():
        for _, param in method_item.items():
            responses = param.get("responses")
            if "422" in responses:
                del responses["422"]

    self.openapi_schema["components"]["schemas"] = {}

    return self.openapi_schema


FastAPI.openapi = openapi

logger = logging.getLogger("uvicorn.error")

config_tmpl = """[Interface]
Address = {{ node.address }}
PrivateKey = {{ node.private }}
ListenPort = 52435
{% for peer in peers %}
[Peer]
Endpoint = {{ peer.ip }}:52435
PublicKey = {{ peer.public }}
AllowedIPs = {{ peer.address }}
PersistentKeepalive = 25
{% endfor %}"""

env = Environment(loader=DictLoader({"config": config_tmpl}))
templates = Jinja2Templates(env=env)


def keys():
    private_key = X25519PrivateKey.generate()
    pubkey = private_key.public_key().public_bytes(encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw)

    bytes_ = private_key.private_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PrivateFormat.Raw, encryption_algorithm=serialization.NoEncryption()
    )

    prv = codecs.encode(bytes_, "base64").decode("utf8").strip()
    pub = codecs.encode(pubkey, "base64").decode("utf8").strip()

    return prv, pub


class CustomRoute(APIRoute):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lock = asyncio.Lock()

    def get_route_handler(self) -> Callable:
        original_route_handler = super().get_route_handler()

        async def custom_route_handler(request: Request) -> Response:
            await self.lock.acquire()
            response: Response = await original_route_handler(request)
            self.lock.release()
            return response

        return custom_route_handler


@asynccontextmanager
async def lifespan(app: FastAPI):
    token = os.getenv("APP_TOKEN")
    if not token:
        token = "testing"
        logger.warning("APP_TOKEN is not set, using 'testing' as X-Auth-Token")
    app.state.token = token
    app.state.cache = TTLCache(maxsize=100, ttl=300)
    yield


description = """
**Yet Another Wireguard Mesh**

Using any generated `uuid` to identify a single mesh (max 100 at the same time), nodes can:
- `register` themselves (they will be identified by their source IP)
- `get` their own config (including all other registered nodes as peers)

All data (registered nodes and keys) expire after 5 minutes.

`X-Auth-Token` header for authentification is sourced from environment variable `APP_TOKEN`

**Use-case**

This tool can be used in a Cloud-Init script during a Terraform execution to:
- register nodes once they are up
- wait a minute or two for everyone
- get the config and install/start Wireguard
"""

app = FastAPI(lifespan=lifespan, title="yawm", description=description, version="1.0.0")
app.router.route_class = CustomRoute


@app.exception_handler(StarletteHTTPException)
async def http_exception_handler(request, exc):
    return PlainTextResponse(str(exc.detail), status_code=exc.status_code)


@app.exception_handler(RequestValidationError)
async def validation_exception_handler(request, exc):
    return PlainTextResponse(str(exc), status_code=400)


@app.get("/favicon.ico", response_class=Response, include_in_schema=False)
async def favicon():
    return Response(media_type="image/x-icon", content=b64decode(favicon_ico))


@app.get("/", response_class=PlainTextResponse, status_code=200, tags=["unlogged routes"])
async def health():
    return "OK"


@app.get("/ip", response_class=PlainTextResponse, status_code=200, tags=["unlogged routes"])
async def check(request: Request):
    source = request.client.host
    return f"Your IP is seen as: {source}"


@app.post("/{uuid}", response_class=PlainTextResponse, status_code=201, tags=["logged-in routes"])
async def register(request: Request, response: Response, uuid: str, x_auth_token: Annotated[str | None, Header()] = None):
    if not x_auth_token or x_auth_token != request.app.state.token:
        response.status_code = 401
        return "Not authenticated"
    source = request.client.host
    if uuid not in request.app.state.cache:
        request.app.state.cache[uuid] = {}
    if source not in request.app.state.cache[uuid]:
        prv, pub = keys()
        request.app.state.cache[uuid][source] = {"private": prv, "public": pub}
        return "Registered"
    response.status_code = 409
    return "Exists"


@app.get("/{uuid}", response_class=PlainTextResponse, status_code=200, tags=["logged-in routes"])
async def get(request: Request, response: Response, uuid: str, x_auth_token: Annotated[str | None, Header()] = None):
    if not x_auth_token or x_auth_token != request.app.state.token:
        response.status_code = 401
        return "Not authenticated"
    source = request.client.host
    if uuid in request.app.state.cache and source in request.app.state.cache[uuid]:
        orderedData = dict(sorted(request.app.state.cache[uuid].items()))
        members = list(orderedData.keys())
        node = {}
        peers = []
        for i in range(len(members)):
            if members[i] == source:
                node["address"] = f"10.0.0.{i+1}"
                node["private"] = orderedData[members[i]]["private"]
            else:
                peer = {}
                peer["address"] = f"10.0.0.{i+1}"
                peer["ip"] = members[i]
                peer["public"] = orderedData[members[i]]["public"]
                peers.append(peer)
        return templates.TemplateResponse(request=request, name="config", context={"node": node, "peers": peers})
    else:
        response.status_code = 404
        return "Not registered or expired"


if __name__ == "__main__":
    uvicorn.run(app="main:app", host="0.0.0.0", port=8080, reload=True, proxy_headers=True, forwarded_allow_ips="*")


favicon_ico = """AAABAAMAMDAAAAEAIACoJQAANgAAACAgAAABACAAqBAAAN4lAAAQEAAAAQAgAGgEAACGNgAAKAAAADAAAABgAAAAAQAgAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaGoAKGhaGOxkXh2YaGIiLGxeIoxoXiLkaF4nEGheIzBoXiMsaF4i0GhiJtxkYiKEbF4eGGheHVxwViiUAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaGoknGxeJexoXiMcaF4j6GheI/xoXiP8aF4j/GheI/xoXiMcaGIlsHRaKIysrgAYAAAAAHByOCRgYiCsaF4h4GhaI2BoXiP8aF4jwGhiIuBsYh2AUFIkNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxiISxsXh8AaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aFojjGheJTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkWiVsaF4jqGheI/xoXiP8aF4j1GheIpRgYiCsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwWiy4aF4i7GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiMggEI8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGYwfGheI1BoXiP8aF4j/GheI/xoXiPwaF4iaHxSFGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BGhaJfxoXiPwaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhaIzSIRiA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRWKGBoXiOEaF4j/GheI/xoXiP8aF4j/GheI7xsXikwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUVgAwbGIitGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j6FxeFLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcHI4JAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkVij0aF4j+GheI/xoXiP8aF4j/GheI/xoXiP0aFoh+AAD/AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHByOCRoXicYaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aGImMAAAAAAAAAAAAAAAAAAAAAAAAAAAXF4sWGRiJlxoXiOwaF4j/GheI6BkXiI4cHI4SAAAAAAAAAAAAAAAAAAAAAAAAAAAaF4mqGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhiJjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKoDGheIrxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8ZGYkpAAAAAAAAAAAAAAAAAAAAABkZiSkaF4jmGheI/xoXiP8aF4j/GheI/xoXiP8aF4jcHRSJGgAAAAAAAAAAAAAAAAAAAAAcGIdAGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xkXiHoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZF4iDGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiNYAAAAAAAAAAAAAAAAAAAAAAACqAxsXidMaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheItAAAAAAAAAAAAAAAAAAAAAAAAIAEGheI8hoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP4aFodGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsWiC8aF4j6GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xsXiKMAAAAAAAAAAAAAAAAAAAAAHBiHQBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/hoaiB4AAAAAAAAAAAAAAAAAAAAAGheJxhoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aFojjHh6HEQAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/ARsXiMoaF4j/GheI/xoXiP8aF4j/GheI/xoXiOYaF4j4GheI/xoXiP8aF4j/GheI/xoYiIsAAAAAAAAAAAAAAAAAAAAAGheJbhoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xgYiEkAAAAAAAAAAAAAAAAAAAAAGheHsRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhaHlQAAAAAAAAAAAAAAAAAAAAAAAAAAGxiISxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiLIiEYgPGRaJWxsYh6IaF4jSGheI+xkXiI4AAAAAAAAAAAAAAAAAAAAAGRaIZxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoWiUUAAAAAAAAAAAAAAAAAAAAAGhiJtxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI+RgYhyAAAAAAAAAAAAAAAAAAAAAAGhiIwxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPsbFIYmAAAAAAAAAAAAAAAAJCSSBxkXiJgAAAAAAAAAAAAAAAAAAAAAHBWKJRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI+B4ehxEAAAAAAAAAAAAAAAAAAAAAGheI1BoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xsXiZkAAAAAAAAAAAAAAAAZGYkpGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4jHJCSSBwAAAAAAAAAAAAAAABsXiKMAAIACAAAAAAAAAAAAAAAAAAAAABoXiKcaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GRiIjQAAAAAAAAAAAAAAAAAAAAAiEYgPGheI/RoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPIXF4sLAAAAAAAAAAAaGIeAGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIuiAQjxAAAAAAAAAAABoYiGsZFYo9AAAAAAAAAAAAAAAAAAAAABISgA4aF4i0GheI/xoXiP8aF4j/GheI/xoXiP8bF4ijKyuABgAAAAAAAAAAAAAAAAAAAAAbGIlfGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8ZFoldAAAAAAAAAAAaF4jPGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoWiOMaGIlhICCACBUVgAwaF4ieAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGRaHURoYiMMaF4j/GheIsBsYiUEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAIaFojNGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8ZFoirAAAAACIRiA8aF4j9GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI9xoXiM8aF4jXGxiJVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGYczGhaIlBoXiIcVFYoYAAAAAAAAAAAAAAAAAAAAABoXiW4aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4juAACABBoWh0YaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/hoWiX8AAKoDGxeIhRwWiy4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUVihgaF4h4GRaIZzMAmQUAAAAAHBiHQBoXiPYaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/HBaLLhsXh3EaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJYwAAAAAAAAAAAACqAxoWiIkbGIlBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxuJHBsXiI8aGIh2GheI9BoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GxaIXhoYiJYaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4eRAAAAAAAAAAAAAAAAAAAAAAAAAAAaF4ljGReHhBoajBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMAmQUbGIeiGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIhxoXiK8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiO0VFYAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACHBiGShoXiOQZF4m1GxaHaBcXiyEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8BGheHsRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJphoWh8IaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiJIAAAAAAAAAAAAAAAAAAAAAAAAAABoXiU4aF4jeGheI/xoXiP8aF4j/GheI5RkXh4QaF4eTGBiKPwAAAAAAAAAAAAAAAAAAAAAAAAAAIBCPEBsXiN0aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIuRoXicYaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xwXhjcAAAAAAAAAAAAAAAAAAAAAGheJThoXiP0aF4j/GheI/xoXiP8aF4j/GheI/xoXiK8AAIACGxaIaRkXiIMAAKoDAAAAAAAAAAAAAAAAAAAAABkWiVIaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhiIwxoXiMUaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xISgA4AAAAAAAAAAAAAAAAAAAAAGheIzBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8cFosuAAAAABgYhiobF4iQAAD/AQAAAAAAAAAAAAAAAAAA/wEaF4fRGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIzBoYiMMaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI7gAAAAAAAAAAAAAAAAAAAAAAAAAAGheI/BoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4diAAAAAAAAAAAaFolFGheJbgAAAAAAAAAAAAAAAAAAAAAZF4hvGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIyBoXh7EaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI+AAA/wEAAAAAAAAAAAAAAAAAAAAAGheI7xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4dXAAAAAAAAAAAAAAAAGheJph4ehxEAAAAAAAAAAAAAAAAcFYolGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJxBoXiJwaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xcXixYAAAAAAAAAAAAAAAAAAAAAGheHpBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPYYGIYVAAAAAAAAAAAAAAAAGRaJUhoXiFoAAAAAAAAAAAAAAAAAAAAAGhaI4xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheHsxoXiHgaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xwYhkoAAAAAAAAAAAAAAAAAAAAAFxeLIRoXiOkaF4j/GheI/xoXiP8aF4j/GheI/hsWh2gAAAAAAAAAAAAAAAAAAAAAHBeILRoWiX8AAAAAAAAAAAAAAAAAAAAAGxeHwBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheInhkWh1EaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiKUAAAAAAAAAAAAAAAAAAAAAAAAAABcXhyIaF4ipGheI8RoXiPsaFojNGRaHUQAAAAAAAAAAAAAAAAAAAAAAAAAAGhWHMRsWh3MAAAAAAAAAAAAAAAAAAAAAGReJtRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhiIgRoaiB4aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPsYGIgrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/AQAAgAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGReHhBoVhzEAAAAAAAAAAAAAAAAAAAAAGhaHwhoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJTgAAAAAaGIjZGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8bF4jKHByOCQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcF4gtGRiIoQAAAAAAAAAAAAAAAAAAAAAAAIACGheI7BoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/HxSFGQAAAAAaGIiWGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheHsxwcjgkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABcXiyEaF4ivEhKADgAAAAAAAAAAAAAAAAAAAAAbF4dCGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aFojjAAAAAAAAAAAaFolQGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiM8bFYowAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxeKTBkXibUYGIYVAAAAAAAAAAAAAAAAAAAAAAAAAAAaF4i7GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aFoifAAAAAAAAAAAgIIAIGheI7RoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j+GheIrxkVh0gVFYAMAAAAAAAAAAAAAAAAEhKADhoXh1caF4i5GReJtR4ehxEAAAAAAAAAAAAAAAAAAAAAAAAAABkXiXAaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8bGIhLAAAAAAAAAAAAAAAAGheHkxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j7GheI3hoXiNQaFojjGheI/xoXiP0aGIeAAACAAgAAAAAAAAAAAAAAAAAAAAAAAAAAGxaHcxoXiP4aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiOUrK4AGAAAAAAAAAAAAAAAAFxeHIhoXiPsaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI7hwYhkoAAAAAAAAAAAAAAAAAAAAAAAAAACQkkgcaFoeVGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xsXiXsAAAAAAAAAAAAAAAAAAAAAAAAAABoWh6AaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJxBoXiLsbGIitFxeHIgAAAAAAAAAAAAAAAAAAAAAAAAAAHRaKIxoXiMwaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI7hsbhhMAAAAAAAAAAAAAAAAAAAAAAAAAABwThBsaF4jyGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI3xkWiVIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaF4dXGheI8RoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheJbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAbFodzGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI3BoXiLIaF4mbGxaIch0UiRoAAAAAAAAAAAAAAAAAAAAAAAAAABsWiHIaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aFojNAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACGhiIuBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI3hgYhzUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoXiNQaF4j/GheI/xoXiP8aF4j/GheI/xoXiPcaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPAcFYckAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxuGExoXiN8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP0aF4i0FxeFLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACsrgAYdFoojGRmHMxkZhzMZGYczGBiIKxUVgAwaFofCGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI+xoXiE8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0WiiMaF4niGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GRmIPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wEZF4hlGhiHdxoXiIcaF4idGReIvxoXiP8aF4j/GheI/xoXiP8aF4j7GxiIVgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdFoojGxeI3RoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4jFICCACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxiJVBoXiP8aF4j/GheI/xoXiPIZFodRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIBCPEBoXiK4aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/hoYiWwAAP8BAAAAADMAmQUbG4YTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZQAAABAgEI8QGRaHUxoXiWMbGIlfGheI8xoXiP8aF4j/GheIzBwViiUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wEZF4hlGheI6BoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiPwaGIjZGhaI2BoXiPkaF4j/GhaIwRUVgAwAAAAAAAAAAAAAAAAAAAAAAAAAABkZiD4aF4j1GheI/xoXiP8aF4j/GheI/xoXiOwaGId1JCSSBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFRWADBoWiX8aF4jtGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xsXidMaF4diFxeFLBkZiTQfFIUZAAAAAAAAAAAcHI4JGheIbRoXiPEaF4j/GheI/xoXiP8aF4jkGhaJfxISgA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAArK4AGGheITxkWiKsaF4jxGheI/xoXiP8aF4j/GheI7xsXh8AaF4iwGhaIfhsXiUMVFYoYGxeJOBoYiYwaF4jpGheI/xoXiP8aF4jfGhaHlRkZiD4AAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIACGhqGKBkWiVsaGImMGhaInxoXiK8aGIi4GheIuxsYiK0aF4iwGxiHohoXh5MbF4dxGxeHQh4ehxEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//4Af//wAA//4D+H//AAD/8A/+D/8AAP/AH/8D/wAA/4A//4H/AAD+AH//wP8AAPwAfg/APwAA+AD8B+A/AADwAPgD4B8AAPAA+APgDwAA4AD4A+AHAADgMPgD4AcAAMA++APgAwAAwB74A+ADAACAD/wH4AMAAIAHfx/AAQAAgAB/z8ABAACAAb//gAEAAIAD3/0AAQAAAAP3/gAAAAAAB/n/AAAAAAAH4D+AAAAAAA/Ab8AAAAAAD4B3wAAAAAAPgH/gAAAAAA+Ae+AAAAAAD4B/4AAAAIAPwP/gAAAAgAfh/+AAAACAB//74AEAAIAD//vgAQAAgAH/9+ABAADAAP/vwAEAAMAAP5/AAwAAwAAAP4ADAADgAAD+AAcAAOAAAfwABwAA8AAH+AAPAAD4AA/wAA8AAPgAP+AAHwAA/AAP/8A/AAD+AA//gH8AAP8AD//w/wAA/4A//+H/AAD/4AD+B/8AAP/4A/wf/wAA//4B4H//AAD//+AP//8AACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKoDHBeGNxoYiWoaF4icGheIuhkXiMkaF4inGReIgxoYiHYZGIiNGReImBkXiGUbFogvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXF4ciGhiIixoXiOUaF4j/GheI/xoXiP8aF4ekFxeHIgAAAAAAAAAAAAAAAAAAAAAXF4UsGxiIrRoXiP8aF4jaGhaIfhsbhhMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXF4sLGhaJihoXiPgaF4j/GheI/xoXiP8aF4j+GReHZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGheIeBoXiP8aF4j/GheI7xsWh3MAAIACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFxeLIRoXh9EaF4j/GheI/xoXiP8aF4j/GheI/xoWiYoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGheInBoXiP8aF4j/GheI/xsWiLYeHocRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkZjB8aF4jmGheI/xoXiP8aF4j/GheI/xoXiP8aF4jsFxeLCwAAAAAAAAAAHByOEhkYiKEaF4j2GheI8RoWh5UcHI4JAAAAAAAAAAAbG4YTGheI9hoXiP8aF4j/GheI/xoXiMsUFIkNAAAAAAAAAAAAAAAAAAAAAAAAAAAaGoAKGheI1RoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiJwAAAAAAAAAAAAA/wEaF4nEGheI/xoXiP8aF4j/GheI/xoXiagAAAAAAAAAAAAAAAAaF4iwGheI/xoXiP8aF4j/GheI/xsWiLYAAP8BAAAAAAAAAAAAAAAAAAAAABkYiI0aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GxaHaAAAAAAAAAAAGBiHNRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/RYWhRcAAAAAAAAAABoYiIEaF4j/GheI/xoXiP8aF4j/GheI/xkWiGcAAAAAAAAAAAAAAAAXF4ciGheI+xoXiP8aF4j/GheI/xoYiJYZF4eEGReIyRoXiPYZFohcAAAAAAAAAAAZFohHGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GRmJKQAAAAAAAAAAGReJeRoXiP8aF4j/GheI/xoXiP8aF4j/GheI6xISgA4AAAAAAAAAABoWiJQaF4j/GheI/xoXiP8aF4j/GheI1RwcjgkAAAAAAACABBkXh2YAAAAAAAAAAB4ehxEaF4j2GheI/xoXiP8aF4j/GheI/xoXiOcAAKoDAAAAAAAAAAAZGImXGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GhiIdgAAAAAzAJkFGheI7BoXiP8aF4j/GheI/xoXiP8aF4j/GheHsyAggAgAAAAAGReJcAAAAAAAAAAAAAAAABkWiV0aF4j4GheI/xoXiP8aF4j1GxeJQwAAAAAAAAAAAAD/ARoYiNkaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4jWAAAAABwYh0AaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI4RkXh2YZFohnGRmIPgAAAAAAAAAAAAAAABwVhyQaFoiUGReIyRkZjB8AAAAAAAAAAAAAAAAaF4hPGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aGoknGxeJexoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoWh5UaF4luGhqMFAAAAAAAAAAAAAAAAAAAAAAgEI8QGxaIXhsXikwAAIACGxuJHBoXiOUaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xkXh2YaFoegGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8ZF4h6AAAAAAAA/wEaF4diGRmJKQAAAAAAAAAAAAAAAAAAAAAAAAAAFRWADBsXh3EbF4jdGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheHkRoXiL0aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GxeHwAAA/wEAAAAAAAAAAAAAAAAbGIlUGheImhoXiE8gIIAIAAAAAAAAAAAAAAAAAAD/ARoXiJwaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4i6GheI1hoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8ZFodRAAAAAAAAAAAkJJIHGxiHohoXiP4aF4j/GheI9BsWh3MZF4dmIBCPEAAAAAAAAAAAJCSSBxoXh9EaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXh9EaGIjZGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/yIRiA8AAAAAAAAAABoXiHgaF4j/GheI/xoXiP8aF4j/GxiIrTMAmQUZF4hvFhaFFwAAAAAAAAAAGheITRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI3BoXiNQaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j1AAAAAAAAAAAAAAAAGheIpxoXiP8aF4j/GheI/xoXiP8aF4jrAAAAAAAAgAIbFol9AAAAAAAAAAAAAP8BGheI5xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4jaGheIuxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aGoAKAAAAAAAAAAAbFol9GheI/xoXiP8aF4j/GheI/xsXh8AAAAAAAAAAABwYhkobFYowAAAAAAAAAAAaF4ekGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiM8aF4iaGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoWh0YAAAAAAAAAACIRiA8aF4jLGheI/xoXiP8aF4jpHBaLLgAAAAAAAAAAGhqIHhsYiVQAAAAAAAAAABoWiYoaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheIuhsWiHIaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheHswAAAAAAAAAAAAAAAAAAqgMbF4lDGheJThQUiQ0AAAAAAAAAAAAAAAAaF4lOHBeILQAAAAAAAAAAGhiHgBoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4eRGhqKMhoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheHZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFBSJDRsWh3MAAAAAAAAAAAAAAAAbGIitGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xkWiV0AAIACGheI6hoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j9GxeIfAAAqgMAAAAAAAAAAAAAAAAAAAAAAAAAABcXhyIbF4iFHByOCQAAAAAAAAAAFxeLIRoXiPYaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/FxeLIQAAAAAaGIiLGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI2xkXiHoaFodGGBiHNRsYiFYaFoifGheIkiQkkgcAAAAAAAAAABoagAoaF4jFGheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoWiM0AAAAAAAAAABkZjB8aF4j8GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI9xoXh2QAAAAAAAAAAAAAAAAfFIUZGheIxxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GReIZQAAAAAAAAAAAAAAABoXiKcaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GxeI3RsWiX0aGooyAAAAAAAAAAAAAAAAGhaJRRoXiOkaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXh+AgIIAIAAAAAAAAAAAAAAAAGhqIHhoXiPQaF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI8RoXiMcaF4ipGxaILwAAAAAAAAAAAAAAABoXiW4aF4j9GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GRaJUgAAAAAAAAAAAAAAAAAAAAAAAAAAGRaJXRoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j2GxaIaRcXiwsAAAAAAAAAAAAAAAAAAAAAGheJmxoXiMsaF4jMGReIyRoXiMgaF4j/GheI/xoXiP8aF4j/GheI/xkXiJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGReIgxoXiP8aF4j/GheI/xoXiP8aF4j/GheI/xoXiP8aF4j/GReHhAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwcjhIZFolSGheIWhoXiMsaF4j/GheI/xoXiP8aF4exKyuABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxeJexoXiP0aF4j/GheI/xoXiP8aF4j/GheI/xkXiMkcFYckAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlAAAABwAAAAAAAAAAGxiHYBoXiP8aF4j/GheImisrgAYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGxeJQxoXiNwaF4j/GheI/xoXiP8aF4j/GheIsBkYiI0aF4inGheJiDMAmQUAAAAAAAAAAAAAAAgaF4hPGheI1xoXiOYaF4j/GheI3xsYiVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKyuABhoYiWoaF4jQGheI/xoXiP8aF4j/GheI+BoXh7MaGIh2GhaJRQAAAAAcE4QbGhaIiRoXiPkaF4j+GheIxRkWiGcrK4AGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYGIYqGRaIZxoXiZsaF4i8GheIuhoWiJQbFol9GRiIjRoXiLIaFoiJGheHWRoaiB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//BP//8D8f/8D/x/+A/8H/AeHg/gHA4HwDwOB8A8DwOB/A4DgP4eAYB/PgGAH/wBAH/4AAB9+AAA8PwAAPB+AADgfgAA8H4AAPD+AIB//gCAf/4BgD/eAYAPPAHAAPgDwAPwA+AD4AfwD8AH8AP+D/wH/x/+APh//4Hh///wj/8oAAAAEAAAACAAAAABACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICCACBkWiFwaF4inGReIvxkXiGUZFYo9GxiHVRoXiJIbGIlUAACABAAAAAAAAAAAAAAAAAAAAAAAAAAAGBiKPxoXh+AaF4j/GheI4R0UiRoAAAAAAAAAAAAAAAAXF4shGheI6hoXiNcbFYowAAAAAAAAAAAAAAAAGBiKPxoXiPkaF4j/GheI/xoXh2QAAAAAGheInhoXiPoaF4eRAAAAABoWiHQaF4j/GheI8RwWiy4AAAAAMwCZBRoXiNoaF4j/GReIyRoXiPAaFYg8GRmMHxoXiP8aF4j/GheI/yAQjxAbF4lDGheI/xoXiP8bF4jKAACAAhsWiF4aF4j/GheI/xoXiKUAAIACGRWKPQAAgAQbF4nTGheI/xoXiMcAAP8BGheHZBoXiP8aF4j/GheI/xoXiU4ZFoirGheI/xoXiP8aF4j/GheI0hsWiHIcHI4JHByOCRkWiVsbF4k4FxeLCxoXiNIaF4j/GheI/xoXiP8aFoegGhaI2BoXiP8aF4j/GheI/xsXiI8AAAAAGxaGORsYiUEAAIACAACABBoWiH4aF4j/GheI/xoXiP8aF4j/GheI0hoXiOoaF4j/GheI/xoXiP8VFYoYGBiHIBoXh+AaF4j8GhiJYRcXiyEAAIACGhiIzhoXiP8aF4j/GheI/xoXiOgaF4niGheI/xoXiP8aF4j8AACAAhgYiEkaF4j/GheI/xoYiGsbFogvFRWADBoYiGsaF4j/GheI/xoXiP8aF4jnGheJxBoXiP8aF4j/GheI/xkZiD4AAIAEGxeIhRoXh5EXF4sLGxuJHBgYhyAaF4dEGheI/xoXiP8aF4j/GheH0RoXiYgaF4j/GheI/xoXiP8aFojYGBiHIAAAAAAAAAAAFRWADBoXiE0AAAAAGhiHdRoXiP8aF4j/GheI/xoXiJ0YGIgrGheI/hoXiP8aF4j/GheI/xoXiPoaF4i5GheJqhoYiWwAAIACGhaIOhoXiPAaF4j/GheI/xoXiP8aFolFAAAAABoXiagaF4j/GheI/xoXiP8aF4j8GheIzxsXiTgAAAAAGhiJbBoXiPkaF4j/GheI/xoXiP8aGIjDAACAAgAAAAAaGowUGheI3hoXiP8aF4j/GheI/RsWiX0AAAAAAAAAABoXiFobF4iFGhiIwxoXiP8aF4jsHBWHJAAAAAAAAAAAAAAAABYWhRcaF4nEGheI/xoXiP8aFoiJGheITQAA/wEAAAALGxiFSxoWiJQaFojNGhqGKAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAhoWiVAaF4ilGheI1BoXiJwaF4dZGxeJexoXiJwbF4pMAACAAgAAAAAAAAAAAAAAAPnfAADj5wAAxjMAAIYxAACOMQAAB+AAAAfgAAAM4AAADPAAAAzwAAAH8AAAgOEAAIHBAADDwwAA4ecAAPjfAAA="""
