name: Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REPO: "${{ github.event.repository.name }}"
  OWNER: "${{ github.repository_owner }}"
  TAG: "${{ github.sha }}"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build image name
        run: |
          echo "IMAGE_NAME=${REPO,,}" >>${GITHUB_ENV}
      - name: Build image tag
        run: |
          echo "IMAGE_TAG=${REGISTRY}/${OWNER,,}/${IMAGE_NAME}:${TAG}" >>${GITHUB_ENV}
          echo "IMAGE_LATEST=${REGISTRY}/${OWNER,,}/${IMAGE_NAME}:latest" >>${GITHUB_ENV}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          provenance: false
          push: true
          tags: |
            ${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_LATEST }}
          labels: |
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: |
            linux/amd64
